_BASE_: ../face-align-base/mask2former_R50_bs32_60k.yaml
MODEL:
  META_ARCHITECTURE: "OpenVocabulary"
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 156
    TEST:
      INSTANCE_ON: True
      PANOPTIC_ON: True
      OVERLAP_THRESHOLD: 0.5
      OBJECT_MASK_THRESHOLD: 0.5
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
  WEIGHTS:
  SEM_SEG_HEAD:
    NAME: "MaskFormerInteractionHead"
    NUM_CLASSES: 8 #only used in set criterion
    EMBEDDING_DIM: 512
    LAND_CLASSES: 125 # D:\python_work\FaceAlignment\Universal Alignment\FreeAlignmentT\mask2former\modeling\transformer\open_transformer_predictor.py line 71
    EMBED_LAYERS: 2
  RESNETS:
    DEPTH: 101
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 2, 4]
  EXTRA:
    AUX_LOSS: True
    KPT_LOSS_COEF: 5.0
    EOS_COEF: 0.1
    DEC_LAYERS: 10
  CLIP_ADAPTER:
    PROMPT_LEARNER: "learnable"
    PROMPT_DIM: 512
    PROMPT_SHAPE: (16, 0)
    CLIP_MODEL_NAME: "ViT-B/16"
    MASK_FILL: "mean"
    MASK_EXPAND_RATIO: 1.0
    MASK_THR: 0.5
    MASK_MATTING: False
    REGION_RESIZED: True
    SEPERATE_ADAPTER: False
    CLIP_ENSEMBLE: True
    CLIP_ENSEMBLE_WEIGHT: 0.8
    PROMPT_CHECKPOINT: './output/prompt_model_0015000.pth'    #  './output/prompt_model_0015000.pth' './output/model_0014999.pth'
INPUT:
  IMAGE_SIZE: 640  
  DATASET_MAPPER_NAME: "mask_former_alignment"
  TASK_NAME: ["300W.",  "COFW.",  "AFLW.", 'WFLW.']

SOLVER:
  IMS_PER_BATCH: 8 #8
  TEST_IMS_PER_BATCH: 1
  MODE: 'predict'
  BASE_LR: 0.00005 # 0.00005 (9-pan)
  WEIGHT_DECAY: 0.00005  # 0.00005 (9-pan)
  WARMUP_FACTOR: 0.001
  MAX_ITER: 60000
  CHECKPOINT_PERIOD: 5001
  LR_SCHEDULER_NAME: WarmupPolyLR
  WARMUP_ITERS: 2500
  WARMUP_METHOD: "linear"
#  LR_SCHEDULER_NAME: WarmupMultiStepLR
#  IMS_PER_BATCH: 8
#  BASE_LR: 0.00005 # 0.00005
#  GAMMA: 0.1
#  WEIGHT_DECAY: 0.001  # 0.00005
#  WARMUP_FACTOR: 0.001
#  WARMUP_ITERS: 2500
#  STEPS: [2500, 20000, 35000]
#  MAX_ITER: 60000
#  CHECKPOINT_PERIOD: 5000
#  WARMUP_METHOD: "linear"
TEST:
  EVAL_PERIOD: 1001

DATASETS:
  TRAIN: ("300W_train",'WFLW_train','COFW_train', 'AFLW_train')  # coco_2017_train_full_task_base_classification "coco_2017_train_stuff_base_sem_seg_classification",
  TEST: ("300W_val", "COFW_val", "AFLW_val", "WFLW_val",) #"COFW_val",  "AFLW_val", "300W_val", "WFLW_val"
  MAX_IMAGE_SIZE: 20000 # AFLW datasets
  SAMPLE_PER_CLASS: 68
  INPUT_SIZE: [ 448, 448 ]
  FLIP: True
  SCALE_FACTOR: 0.25
  ROT_FACTOR: 30
  NUM_LANDMARKS: 68
  LANDMARK_INDEX_300W: [ 1, 3, 5, 8, 11, 15, 19, 22, 24,  # left chin (0-8) 24 chin center
                         26, 30, 33, 37, 40, 42, 45, 48,  # right chin (9-16)
                         49, 50, 51, 52, 53, 58, 59, 60, 61, 62,  # brow (17-26)
                         67, 68, 69, 70, 71, 72, 73, 74, 75,   # nose 9 (27-35)
                         78, 80, 83, 84, 86, 88, 90, 91, 94, 96, 98, 100, # eyes 12 (36-47)
                         102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, # mouth 20 (48-67)
                         124 ] #background
  LANDMARK_INDEX_COFW: [ 49, 62, 53, 58, 51, 56, 60, 64,  # brow 8 (0-7)
                         78, 96, 84, 90, 81, 87, 93, 99,  # eyes 8 (8-15)
                         122, 123, #pupil 2 (16, 17)
                         76, 77, 70, 73,  # //nose 4 (18-21)
                         102, 108, 105, 116, 120, 111,  # mouth 6 (22-27)
                         24, # chin 1  (28)
                         124 ] #background
  LANDMARK_INDEX_WFLW: [ 0, 2, 4, 6, 7, 9, 10, 12, 13, 14, 16, 17, 18, 20, 21, 23, 24,  # left chin (0-16) 24 chin center
                         25, 27, 28, 29, 31, 32, 34, 35, 36, 38, 39, 41, 43, 44, 46, 47,  # right chin (17-32)
                         49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,  # brow (33-50)
                         67, 68, 69, 70, 71, 72, 73, 74, 75,  # nose 9 (51-59)
                         78, 79, 81, 82, 84, 85, 87, 89, 90, 92, 93, 95, 96, 97, 99, 101,  # eyes 16 (60-75)
                         102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, # mouth 20 (76-95)
                         122, 123, # pupil 2 (96-97) background
                         124 ] #background

  LANDMARK_INDEX_AFLW: [ 49, 51, 53, 58, 60, 62,  # brow 6 (0-5)
                         78, 122, 84, 90, 123, 96,  # eyes 6 (6-11)
                         76, 70, 77,  # nose 3 (12-14)
                         102, 120, 108,  # mouth 3 (15-17)
                         24, # chin 1 (18)
                         124 ] #background
  BOUNDARY: [ 'left contour', 'right contour', 'left brow', 'right brow', 'nose', 'left eye', 'right eye',  'mouth']
    #  LANDMAKR_BOUNDARY_300W: [[1, 3, 5, 8, 11, 15, 19, 22, 24],
    #                           [26, 30, 33, 37, 40, 42, 45, 48],
    #                           [49, 50, 51, 52, 53],
    #                           [58, 59, 60, 61, 62],
    #                           [67, 68, 69, 70, 71, 72, 73, 74, 75],
    #                           [78, 80, 83, 84, 86, 88],
    #                           [90, 91, 94, 96, 98, 100],
    #                           [102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121]]
  LANDMAKR_BOUNDARY_300W: [ [ 0, 1, 2, 3, 4, 5, 6, 7, 8 ], [ 9, 10, 11, 12, 13, 14, 15, 16 ], #left, right chin
                              [ 17, 18, 19, 20, 21 ], [ 22, 23, 24, 25, 26 ], #left right brow
                              [ 27, 28, 29, 30, 31, 32, 33, 34, 35 ], #nose
                              [ 36, 37, 38, 39, 40, 41 ], [ 42, 43, 44, 45, 46, 47 ], #left right eye
                              [ 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67 ] ] #mouth
  LANDMAKR_BOUNDARY_COFW: [ [ 28 ], [ ], #left, right chin 1
                              [ 0, 2, 4, 5 ], [ 1, 3, 6, 7 ], #left right brow 8
                              [ 18, 19, 20, 21 ], #nose 4
                              [ 8, 10, 12, 13, 16 ], [ 9, 11, 14, 15, 17 ], #left right eye 10
                              [ 22, 23, 24, 25, 26, 27 ] ] #mouth 6

  LANDMAKR_BOUNDARY_AFLW: [ [ 18 ], [ ], #left, right chin 1
                              [ 0, 1, 2 ], [ 3, 4, 5 ], #left right brow 8
                              [ 12, 13, 14 ], #nose 4
                              [ 6, 7, 8 ], [ 9, 10, 11 ], #left right eye 10
                              [ 15, 16, 17 ] ] #mouth 6

  LANDMAKR_BOUNDARY_WFLW: [ [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 ], [ 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32 ], #left, right chin
                              [ 33, 34, 35, 36, 37, 38, 39, 40, 41 ], [ 42, 43, 44, 45, 46, 47, 48, 49, 50 ], #left, right brow
                              [ 51, 52, 53, 54, 55, 56, 57, 58, 59 ], # nose
                              [ 60, 61, 62, 63, 64, 65, 66, 67, 96 ], [ 68, 69, 70, 71, 72, 73, 74, 75, 97 ], #left right eye
                              [ 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95 ] ] #mouth
